### PR TITLE
added gzip support

### PR DESCRIPTION
**Pull request by ferronrsmith**

### CODE REVIEW

**Comment by DavidBord** [comment]
I would apply the following changes:
- Add an explicit compression flag to the upstream config when compression is applied: ContentType: 'application/gzip'
- The default record key should contain a gz suffix when compression is applied
- Maybe concat .gz suffix to the --s3RecordKey if it is not provided?

**Comment by ferronrsmith** [comment]
1. I don't think the upstream lib allows the content-type to be configured. Not sure it's important since it's being sent as a multi-part anyway
1. The problem with concatenating suffixes is that you have to check if it's already there. It's easy to do `--s3RecordKey=blah.tar.gz`. 

I have no means of testing this. So I weary of adding additional changes anyway

**Comment by DavidBord** [comment]
1. It is allowed. It has nothing to do with the upload, it has to do with the download - could auto gunzip on the supported clients.
One last suggestion: instead of supporting 2 forms of gzip - through stdout while assuming the underlying OS has gzip installed and through zlib with --s3Compress flag - I suggest using just one flag --gzip or --compress with gzip as a possible value that will always use zlib.
Regarding the testing - I'll happily test it

**Comment by ferronrsmith** [comment]
We don't support download/import from s3 https://github.com/taskrabbit/elasticsearch-dump/issues/503. Thing is we support users importing their own transport; If someone contributes it, I'll happily merge, but beyond that their will be no future development from me on this feature. 

It's not 2 forms of gzip. stdout allows you to pipe your output to anything. This is just an OS level function.

**Comment by DavidBord** [comment]
Nevermind.
Anyway, I tested it, it is working and you can merge it if you want

**Comment by ferronrsmith** [comment]
I'm removing compression from the file transport. If it needs to be compressed it can be piped to a compression program or the transport overridden.

**Pull request merged**
