### PR TITLE
Fix the use of extraFields

### PR DESCRIPTION
**Pull request by gnujeremie**
Issue #166

### CODE REVIEW

**Comment by evantahler** [comment]
Note that this change breaks the test suite, so it broke some functionality elsewhere...

**Comment by gnujeremie** [comment]
Yes, I saw that. I'll fix this!

**Comment by gnujeremie** [comment]
Sorry for the live tests, my current workstation is not fully set up :-/

**Comment by evantahler** [comment]
Looks good now, but please also add a test so that your fix will be 'locked in' for the future, and will help explain your changes.

**Comment by gnujeremie** [comment]
Okay no problem.
However, I'm not familiar with travis, can I install what's needed for the tests suite on my computer and try it before pushing more commits ?

**Comment by evantahler** [comment]
absolutely! 

You'll need node.js and npm, obviously.
You'll also need elasticsearch (version 1.x, we've got another story to upgrade things to v2, but that's later)
- download your fork locally and `cd` into that directory
- run `npm install`, that will install the depandancies listed here (https://github.com/taskrabbit/elasticsearch-dump/blob/master/package.json#L16-L24)
- run `npm test` (which is shorthand for running `./node_modules/.bin/mocha`, as defined in the `package.json`).  

That's all travis does!

**Comment by gnujeremie** [comment]
Thanks a lot !

I understand now why the tests suite was broken before, I did not realise it was specifically for ES 1.x. I am using ES 2.x. 
Maybe my fix is not relevant then... what do you think ?

**Comment by evantahler** [comment]
please still move forward with it!   We need to get this tool up to speed with ES 2

**Comment by gnujeremie** [comment]
LOL okay i'll see what I can do then :)

**Comment by evantahler** [comment]
I've just removed bulk mode entirely from this project.  
Your fix here only effected 'bulk'

**Comment by evantahler** [comment]
Bump! 
Do you need any help here?

**Comment by evantahler** [comment]
closing in favor of https://github.com/taskrabbit/elasticsearch-dump/pull/202

**Pull request closed without merging**
