### PR TITLE
PR for #491 Allow TLS X509 client authentication

### PR DESCRIPTION
**Pull request by morningspace**
Just a draft version to see if that's ok to go forward. It's been tested locally. To use it, add ssl options as command line arguments when launch elasticdump, e.g. --cert, --key,  --ca, etc. Then, the tool will pick up the cert and key files when exist.

### CODE REVIEW

**Comment by ferronrsmith** [comment]
This looks good. Let me know when you are ready to merge

**Comment by morningspace** [comment]
Hey @ferronrsmith Here it is:-)

Also updated the docs. It's a bit tedious since both input and output need to be considered. But the good thing is the new options are easy to understand & remember, also most of them are just optional. e.g. if source and dest point to the same server, we could simply use: --cert, --key, and --pass.

Does it make sense?

**Comment by ferronrsmith** [comment]
Yup👍🏾

**Comment by morningspace** [comment]
Hi @ferronrsmith Do you think if it's ok to merge or there's anything else needs me to tweak?

**Comment by ferronrsmith** [comment]
I don’t like the fact that applySSL is always called, the implementation before was a little better. It should only be called when the necessary params are passed

**Comment by morningspace** [comment]
Hey @ferronrsmith sorry for the late response... was just back to it after a few days' working on other stuff and noticed that you've updated and merged... It's awesome! nice addition! 👍

**Pull request merged**
