### PR TITLE
First try to add custom certificate support.

### PR DESCRIPTION
**Pull request by admlko**
So here's the PR what I'm trying to achieve.

When I call elasticdump directly, it works as expected:

```
0369497e1886:/# elasticdump --input=https://elasticdump:elasticdump@elasticsearch:9200/testing* --output=/testi/testing.json --tlsAuth --cert=/cert.pem --key=/key.pem --ca=/ca.pem
Mon, 06 May 2019 08:20:44 GMT | starting dump
Mon, 06 May 2019 08:20:44 GMT | got 100 objects from source elasticsearch (offset: 0)
Mon, 06 May 2019 08:20:44 GMT | sent 100 objects to destination file, wrote 100
Mon, 06 May 2019 08:20:44 GMT | got 87 objects from source elasticsearch (offset: 100)
Mon, 06 May 2019 08:20:44 GMT | sent 87 objects to destination file, wrote 87
Mon, 06 May 2019 08:20:44 GMT | got 0 objects from source elasticsearch (offset: 187)
Mon, 06 May 2019 08:20:44 GMT | Total Writes: 187
Mon, 06 May 2019 08:20:44 GMT | dump complete
```

But when I call multielasticdump:
```
0369497e1886:/# multielasticdump --input=https://elasticdump:elasticdump@elasticsearch:9200 --output=/testi --match='^(?!\.).*$' --tlsAuth --cert=/cert.pem --key=/key.pem --ca=/ca.pem
Mon, 06 May 2019 08:29:24 GMT | We are performing : dump
Mon, 06 May 2019 08:29:24 GMT | options: {"debug":true,"parallel":2,"match":"^(?!\\.).*$","input":"https://elasticdump:elasticdump@elasticsearch:9200","output":"/testi","scrollTime":"10m","timeout":null,"limit":100,"offset":0,"direction":"dump","support-big-int":false,"ignoreAnalyzer":false,"ignoreData":false,"ignoreMapping":false,"ignoreSettings":false,"ignoreTemplate":false,"ignoreAlias":true,"ignoreType":[],"interval":1000,"prefix":"","suffix":"","transform":null,"searchBody":null,"cert":"/cert.pem","key":"/key.pem","pass":null,"ca":"/ca.pem","tlsAuth":true,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null}
Mon, 06 May 2019 08:29:24 GMT | Error: unable to verify the first certificate
```

### CODE REVIEW

**Comment by admlko** [comment]
@ferronrsmith do you have any idea why this doesn't work?

**Comment by ferronrsmith** [comment]
did u test this with your branch ? Seems current. Try running it inside the folder


`./bin/multielasticdump`

**Comment by admlko** [comment]
Yes, I am sure about the branch and the multielasticdump executable.

**Comment by ferronrsmith** [comment]
That’s strange, can your run it debug mode and post the output ?

**Comment by admlko** [comment]
Debug is already enabled in the first post, at least it says "debug":true.
Same results if I add --debug.

Thank you for looking into this :)

**Comment by ferronrsmith** [comment]
the debug isn't being passed through to elasticdump. The debug multielasticdump isn't verbose enough.

**Comment by admlko** [comment]
I added `--debug=${options.debug}` at the end of each fork args but I get the same results.

**Comment by ferronrsmith** [comment]
trying to avoid creating a proxy to test this, but I might have to.

Test this PR : https://github.com/taskrabbit/elasticsearch-dump/pull/544.

If it doesn't work then I'll configure a proxy to test.

**Comment by admlko** [comment]
> trying to avoid creating a proxy to test this, but I might have to.

I know, I am trying to provide as much information as I can so you wouldn't have to set it up :)

> Test this PR : #544.

Same results:

```
# ./bin/multielasticdump --input=https://elasticdump:elasticdump@elasticsearch:9200 --output=/root/elasticdump-data --tlsAuth --cert=/root/certs/cert.pem --key=/root/certs/key.pem --ca=/root/certs/root-cert.pem
Thu, 16 May 2019 06:09:06 GMT | We are performing : dump
Thu, 16 May 2019 06:09:06 GMT | options: {"debug":true,"parallel":2,"match":"^.*$","input":"https://elasticdump:elasticdump@elasticsearch:9200","output":"/root/elasticdump-data","scrollTime":"10m","timeout":null,"limit":100,"offset":0,"direction":"dump","support-big-int":false,"ignoreAnalyzer":false,"ignoreData":false,"ignoreMapping":false,"ignoreSettings":false,"ignoreTemplate":false,"ignoreAlias":true,"ignoreType":[],"interval":1000,"prefix":"","suffix":"","transform":null,"searchBody":null,"cert":"/root/certs/cert.pem","key":"/root/certs/key.pem","pass":null,"ca":"/root/certs/root-cert.pem","tlsAuth":true,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null}
Thu, 16 May 2019 06:09:06 GMT | Error: unable to verify the first certificate
```

And with elasticdump:
```
# ./bin/elasticdump --input=https://elasticdump:elasticdump@elasticsearch:9200/test* --output=/root/elasticdump-data/test.json --tlsAuth --cert=/root/certs/cert.pem --key=/root/certs/key.pem --ca=/root/certs/root-cert.pem
Thu, 16 May 2019 06:17:25 GMT | starting dump
Thu, 16 May 2019 06:17:25 GMT | got 100 objects from source elasticsearch (offset: 0)
Thu, 16 May 2019 06:17:25 GMT | sent 100 objects to destination file, wrote 100
Thu, 16 May 2019 06:17:25 GMT | got 87 objects from source elasticsearch (offset: 100)
Thu, 16 May 2019 06:17:25 GMT | sent 87 objects to destination file, wrote 87
Thu, 16 May 2019 06:17:25 GMT | got 0 objects from source elasticsearch (offset: 187)
Thu, 16 May 2019 06:17:25 GMT | Total Writes: 187
Thu, 16 May 2019 06:17:25 GMT | dump complete
```

> NB: Have you tried using the full path to the cert ?

Yup.

**Comment by ferronrsmith** [comment]
Ok thanks I’ll just have to do a full test end to end

**Comment by ferronrsmith** [comment]
Ok found the issue. Can you retest PR https://github.com/taskrabbit/elasticsearch-dump/pull/544.

Thanks for being patient

**Comment by admlko** [comment]
Damn, I still get the same...

**Comment by ferronrsmith** [comment]
u got the latest code ? are u sure ?

**Comment by admlko** [comment]
I removed the elasticsearch-dump folder I had cloned before, cloned your repository again and called:
`git pull origin pull/544/head:544`

Changed to the PR branch by calling:
`git checkout 544`

Checked that the elasticdump and multielasticdump executables has the most recent modifications and ran the multielasticdump locally (./bin/multielasticdump bla bla).

**Comment by ferronrsmith** [comment]
According to the docs, this error only suppose to happen if the cert is invalid
Run the following command, then re-run multielasticdump and see if it works.
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by admlko** [comment]
So after ignoring the certificate warnings, it works.
But why...
The certs works great with elasticdump and other clients.

**Comment by ferronrsmith** [comment]
Wondering if the very is somehow invalid or not being validated by the CA

**Comment by ferronrsmith** [comment]
hard to say without the cert, but my guess is that it wasn't validated with a CA.

**Comment by admlko** [comment]
The certificate is fine, it works with Logstash, Elastic Curator and ElastAlert. I can manually verify it against the CA certificate with openssl verify. And it also works fine with elasticdump, but not with multielasticdump.

Anyway, I have just left for paternity leave so thank you for merging this feature and I might check on it later on in the fall.

**Comment by ferronrsmith** [comment]
Ok np and congrats 🎉.

**Pull request merged**
