### PR TITLE
run --transform in global context

### PR DESCRIPTION
**Pull request by darky**
This give me access to all node.js stuff, that needed for difficult transformation scripts

### CODE REVIEW

**Comment by evantahler** [comment]
Seems pretty dangerous... can you share what context you want access to?

**Comment by darky** [comment]
> Seems pretty dangerous... 

Sorry, but I don't understand what mean is dangerous. You mean, that I pass some "virus" code in `transform` and totally destroy all my infrastructure?))

> can you share what context you want access to?

I want to use maximum power of node.js. In my case, need to generate special `doc._id` via some libs, that need to be required in `transform`. Sorry, but it incomplete now in this PR, as it turned out, `runInThisContext` not enough.

**Comment by datashaman** [comment]
+1

This script is being run by an administrator on the CLI, where does untrusted code come into play?

Sure, if you ask the web app user to input the code used in the transform, it will be unsafe.

But that's not happening here. This is a server-side CLI. You are entering the code, in the same way as writing it in a source file would be.

It's as safe as the account writing the code and running the command.

**Comment by datashaman** [comment]
I would (for example) like to anonymize data going through the pipe. Doing that in a string parameter without access to globals is very difficult, I would have to manually recreate all the resources I need (within the constraints of a command parameter string).

**Comment by datashaman** [comment]
@darky I have a neat solution incoming as another PR.

**Comment by evantahler** [comment]
@datashaman thanks to your other PR, this can't be merged now... can you please update?

**Comment by evantahler** [comment]
Whoa... Github has a new online merge-conflict fixer!

**Pull request merged**
