### PR TITLE
Added analyzer support

### PR DESCRIPTION
**Pull request by jeffyuhaoliu**

### CODE REVIEW

**Comment by evantahler** [comment]
good start!
Let me know when you get the test suite passing.

**Comment by jeffyuhaoliu** [comment]
hi evan, the test suit is passing now.

**Comment by evantahler** [comment]
Nice!  Thanks!
I'm sure in the future there will be some discussion about renaming this to `settings` or something like that, but lets get it out there now!

**Comment by evantahler** [comment]
```
> npm publish
+ elasticdump@0.17.0
```

**Comment by jeffyuhaoliu** [comment]
Thanks Evan!

**Pull request merged**
