### PR TITLE
Moving Docker image to Alpine Linux

### PR DESCRIPTION
**Pull request by khanhicetea**
Move base image to Alpine Linux to reduce image size (only 33.56 MB instead of ~350 MB)

### CODE REVIEW

**Comment by evantahler** [comment]
This branch can no longer be merged.  Please update from master

**Comment by evantahler** [comment]
what version of node does Alpine ship with now (we need v1 or greater, v4 LTS preferred)?  Is there no value on using a more "common" version of linux?

**Comment by khanhicetea** [comment]
It's default Node package of Alpine (v4 LTS). All official docker images are moving to Alpine instead of Ubuntu or Debian.

I think using lightweight image is better, we have what we need.
Btw, I will rebase the branch if you agree :smiley:

**Comment by evantahler** [comment]
Cool, looks like you are right, and all the official containers are moving to alpine.  
Ship it!

**Comment by khanhicetea** [comment]
:+1: It's ready !

**Comment by evantahler** [comment]
```
> npm publish
+ elasticdump@1.0.3
```

**Pull request merged**
