### PR TITLE
Add HTTP auth by ini file

### PR DESCRIPTION
**Pull request by tarrow**
This is a patch to enable reading HTTP credentials from an ini file.

This is important because otherwise, on a multi user system, you leak credentials through the process list.

I chose to use an ini because that is what the AWS credentials code also seems to use.

I brought up an issue about this before in #269 for reference.

### CODE REVIEW

**Comment by evantahler** [comment]
This branch cannot be merged.   Please rebase against mater.

**Comment by tarrow** [comment]
I've now rebased against the latest master.

Let me know if there are any changes or alterations you'd like me to make.

Thanks. :)

**Comment by evantahler** [comment]
👍

**Comment by evantahler** [comment]
v3.1.0 is released with this update

**Pull request merged**
