### PR TITLE
Improve the performance of copying data from a slow input to a slow output

### PR DESCRIPTION
**Pull request by igelbox**
**The idea:**
 is to overlap waitings for input and output completion to allow fetching the next portion of data while the previous portion is saved. It would be easy to explain the difference using a timing diagram:
```js
Time:  |-> -> -> -> -> -> -> -> -> -> ->|
/* The original algorithm:*/            |
Input: | Gggg   Ggggg     Ggg   Gggg    |
Output:|     Sss     Sssss   Sss    Ssss|
/* The new algorithm:*/        |        |
Input: | GgggGggggGgg  Gggg    |<PROFIT>|
Output:|     Sss  SssssSss Ssss|        |
```
**Performance testing:**
 by copying 3000 documents (about 39MB JSON data) between two Elasticsearch clusters (both using remote instances). Both algorithms were started at the same time to have the same impact from a network and/or the cluster load.
The existing algorithm:
> 2.94s user 0.53s system 2% cpu 2:12.68 total
> 2.94s user 0.42s system 2% cpu 2:30.21 total

The new algorithm:
> 2.86s user 0.50s system 3% cpu 1:35.33 total
> 2.98s user 0.44s system 3% cpu 1:51.73 total

So, it's about 35% performance boost.

**Drawbacks:**
To deal with complexity, I had to refactor the original algorithm using promises `async/await` NodeJS features. And this led me to the following drawbacks:
1. I don't see an appropriate way to call the `callback` with both `err` and `totalWrites` arguments. So, in an exceptional case, I just pass the `err` argument in the callback.
2. NodeJS barks if the `callback` function has thrown an exception. To be honest, currently, it's not clear for me, what is the default NodeJS' behavior for callback-style algorithms. But, after this fix, NodeJS will threaten to kill the process in case of an unhandled promise rejection.

### CODE REVIEW

**Comment by ferronrsmith** [comment]
Thanks for your contributions. 

All I see is a conversion from using callbacks to using promises. Not sure where exactly the performance boost comes from.

**Comment by igelbox** [comment]
@ferronrsmith the latest f780c43fb0ebb2b588e0cc5116f33073365f2575 commit brings the performance.
Yeah, I had to refactor the code to use promises, otherwise, I would have to do a tricky stuff with closures.
Anyway, if you have an idea of how to implement this approach using callbacks and closures, please, let me know.

**Comment by ferronrsmith** [comment]
it's cool,  don't mind your contribution. Just wanted an explanation. I'll run a few tests first then I'll merge thanks.

**Comment by ferronrsmith** [comment]
Another issue I see with this change. Because you're sending data to the ES concurrently, there will be instances where it suffers from a `Fast producer and slow consumer` issue. Especially id the **refresh_interval** if ES is low.

**Comment by igelbox** [comment]
Sorry, I didn't get your point about the `Fast producer and slow consumer` issue.
This implementation waits until the previous portion of data has been sent before getting a next one. So, we may have at most 1 portion of data in memory. E.g. in the timing diagram example, the 4th get request `Gggg` will start only after the 2nd send request `Sssss` has been finished:
```js
Input: | GgggGggggGgg  Gggg    |<PROFIT>|
Output:|     Sss  SssssSss Ssss|        |
```
Also, this implementation doesn't try to execute two parallel get requests nor two parallel send requests. It just allows to overlap one "send" request with a "get" one.

Anyway, I was thinking on a previous comment "All I see is a conversion from using callbacks to using promises." and could you please postpone merging this MR a couple days? I believe I have an idea how to implement this algorithm without using Promises, so, I wanna try this.

**Comment by ferronrsmith** [comment]
No problem

**Comment by ferronrsmith** [comment]
Btw, I don’t have a problem with the promise implementation. It works, and from my testing it seems fine

**Comment by igelbox** [comment]
Sorry for such a delay. A couple of months ago I tried to re-implement this on callbacks rather than promises but with no success. I thought I try once again, but, days are getting warmer (summer is coming) and will to code is getting weaker )
So, if you don't mind yet let's merge this as it is.

**Comment by ferronrsmith** [comment]
not really seeing any performance gains from this change after retesting. Think we should shelf this for now. Thanks for your contribution

**Comment by igelbox** [comment]
Weird. Did you try it using two separated ES instances?
I mean if there was just single then it may use all the performance just to a single read or write step so there will be no benefit to overlap team on instance under a high load.

I tried to measure the benefit once again and get a slight improvement if I dump a remote (several thousand kilometers away) ES index into a local Docker-powered ES  ~ 3:44 or so using `master` branch vs 3:27 using my fix (the command was like `./bin/elasticdump --size=3000`):
* The `master`-branch algorithm:
**  6.22s user 1.07s system 3% cpu 3:44.19 total
**  6.00s user 1.17s system 3% cpu 3:49.49 total
* The new algorithm:
**  6.64s user 1.12s system 3% cpu 3:27.61 total
**  6.28s user 1.30s system 3% cpu 3:35.57 total

**Comment by ferronrsmith** [comment]
Thanks for sticking with this.

**Comment by ferronrsmith** [comment]
Just to note there were 2 problems with this change.

1. It introduced a race condition, which in turn led to variable leaking (which was resolved by changing scope)
1. All records weren't being processed in all cases since the logic didn't wait until all promises were resolved.
1. Order is no longer guaranteed due to parallel processing.

It's optimization induced by parallel processing, but draw-backs to this is order is no longer guaranteed. Which means this can't be used `historical indexing`, where variations of changes to a single record maybe be a part of a single payload.

**Comment by igelbox** [comment]
Weird. I don't expect any out of orders. The only thing can overlap is write over read and read over write. Lemme do a static check today. Or, even better, do you have a scenario to reproduce these bugs or make them happen more frequently?

**Comment by ferronrsmith** [comment]
https://github.com/taskrabbit/elasticsearch-dump/issues/568 (the data isn't index in order)

https://github.com/taskrabbit/elasticsearch-dump/blob/master/test/test.js#L741 (the output `/tmp/out.json`

The order isn't really a problem unless you're doing historical updates. Which isn't really the purpose of this tool. It does have perf benefits, but this is a drawback due to the overlapping

**Comment by igelbox** [comment]
Well, I figured it out. The issue in the `file` transport actually. Due to `stream` never paused (we pause `metaStream` only) we may get several subsequent `thisGetCallback` calls.
Previous 6.0.2 version were triggering several concurrent `output.set` requests which might cause some race conditions I believe.
New version uses Promise-s (e.g. `promisify(this.input.get)`) so we simply lose all `thisGetCallback` calls except the last one (which brings us an empty array).

**Pull request merged**
