### PR TITLE
Support insecure mode for https transport

### PR DESCRIPTION
**Pull request by fno2010**

### CODE REVIEW

**Comment by evantahler** [comment]
ElasticDump is looking for a new maintainer(per #333). We have one volunteer so far, but we can always use more! @fno2010  are you interested in helping out? 

This PR is missing a test... however, without creating our own HTTPS server within the test suite, I think writing a test here would be more trouble then it would be worth.  What are your thoughts @datashaman?

**Comment by ebuildy** [comment]
Very nice PR!

How can we add a test on it ? (with a nginx in front of ES maybe)

**Comment by evantahler** [comment]
I would argue this is no needed, as you can set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` to obtain the same behavior.
 
This could be added to the README to make it more clear.

**Comment by ebuildy** [comment]
Absolutely!

**Comment by evantahler** [comment]
@ebuildy Since we agree, please close this out, and add a section to the README about it!

**Comment by ferronrsmith** [comment]
added not to README.md

**Pull request closed without merging**
