### PR TITLE
added support for Amazon Request Signing 4

### PR DESCRIPTION
**Pull request by thomasheckmann**
If you are using Amazon Elasticsearch hosted solution, you have probaly protected the service using IAM roles. In that case you need to sign every request to Elasticsearch with Signature Version 4. This patch makes use of 'aws4' to create correct signing when using the REST API.

* http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html
* https://www.npmjs.com/package/aws4

### CODE REVIEW

**Comment by evantahler** [comment]
cool!

Can you please add some tests for this?

**Comment by thomasheckmann** [comment]
Sure.. will figure out how much can be tested without having access to an AWS Elasticsearch instance.

**Comment by evantahler** [comment]
Even adding a test that that `request` payload is formed properly with the right keys would be a step in the proper direction.

**Comment by thomasheckmann** [comment]
refactored aws stuff to seperate module and added test cases.

**Comment by evantahler** [comment]
Great! Thanks!

**Comment by evantahler** [comment]
I'm making some slight modifications to your API here https://github.com/taskrabbit/elasticsearch-dump/pull/240

Once green, I'll release version `2.4.0` of elasticdump, which will have this included!

Thanks again!

**Comment by evantahler** [comment]
up! https://github.com/taskrabbit/elasticsearch-dump/releases/tag/v2.4.0

**Pull request merged**
