### PR TITLE
671_Enable_Search_Templates | :tada: Initial commit.

### PR DESCRIPTION
**Pull request by mgorsk1**

### CODE REVIEW

**Comment by mgorsk1** [comment]
Links to https://github.com/taskrabbit/elasticsearch-dump/issues/671

**Comment by ferronrsmith** [comment]
You need to run `./node_modules/.bin/standard --fix`

**Comment by ferronrsmith** [comment]
still failing https://travis-ci.org/taskrabbit/elasticsearch-dump

**Comment by mgorsk1** [comment]
Thanks for the fixes, on localhost standard --fix did not produce any errors, probably different node version or linting config ?

**Comment by ferronrsmith** [comment]
yea maybe

**Pull request merged**
