### PR TITLE
es 6 support: add bulk right content type

### PR DESCRIPTION
**Pull request by ebuildy**
According https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html:

> NOTE: the final line of data must end with a newline character \n. Each newline character may be preceded by a carriage return \r. When sending requests to this endpoint the Content-Type header should be set to application/x-ndjson.

Should fix:

- #357
- #350

### CODE REVIEW

**Comment by jacol12345** [comment]
Is there any plan for merging this PR? Lack of it makes elasticsearch-dump useless with ES 6.

**Comment by evantahler** [comment]
ElasticDump is looking for a new maintainer(per https://github.com/taskrabbit/elasticsearch-dump/issues/333).  We have one volunteer so far, but we can always use more!  @ebuildy are you interested in helping out?

This PR is missing a test.  Since it intends to add support for ElasticSearch v6, the Travis.CI test suite should also test this version.  This can be configured here: https://github.com/taskrabbit/elasticsearch-dump/blob/master/.travis.yml

After a successfully merged PR (with adequate tests), I'm happy to make you a maintainer @ebuildy.

**Comment by ebuildy** [comment]
D'oh!

ES 6 do not support multiple ``type`` by ``index`` and ``form`` in scroll search, hence some test are failing.

See https://travis-ci.org/taskrabbit/elasticsearch-dump/jobs/312007553.

**Comment by evantahler** [comment]
I'm happy updating this tool to require node v8+.  You'll need to change:
* package.json#engines https://github.com/taskrabbit/elasticsearch-dump/blob/master/package.json#L27
* travis.yml https://github.com/taskrabbit/elasticsearch-dump/blob/master/.travis.yml#L6-L7

**Comment by ebuildy** [comment]
Hello, what the status of this?

**Comment by evantahler** [comment]
It looks like the tests dont pass for ES v6?

**Comment by ebuildy** [comment]
Yes, multiple types are no more.

**Comment by jayjanssen** [comment]
Just don't rip types out yet -- ES6 won't support types on new indexes, but it will support existing types on 5.x indexes.

I haven't tested it, but I'm wondering if you can work around for tests in 6.x by setting index.mapping.single_type: false

**Comment by tvb** [comment]
@jayjanssen any idea how to set this during elasticdump run?

**Comment by evantahler** [comment]
I'm going to merge this in to master now, as it is certainly the right direction to solve the problems with ElasticSearch 6.  @ebuildy you are also now a maintainer of this project!  

Please work with @ferronrsmith (and https://github.com/taskrabbit/elasticsearch-dump/pull/376) to come up with a way to get the tests passing for all Elasticsearch versions, or decide to only support certain versions going forward.

**Comment by jayjanssen** [comment]
@tvb  - unfortunately the ES devs decided to make it impossible to create a typed index in ES 6, see my argument with them here:  https://discuss.elastic.co/t/creating-new-types-in-6-0/111350

**Pull request merged**
