### PR TITLE
Add type=settings options

### PR DESCRIPTION
**Pull request by bloublou2014**
Add type=settings to export/import whole index settings
Since some options like number_of_shards cannot be set if output index exists, an error is throw if output index exists.

This functionality is useful during backup/restore index. Currently elasticdump create a new index without saved index settings, leading to unwanted shards or replicas default setting.

Important : this is my first functionality commit, if a process has to be fulfilled or function is not appropriate, fell free to reject this pull request.

### CODE REVIEW

**Comment by bloublou2014** [comment]
Error on ci. i will check before pulling again.

**Comment by evantahler** [comment]
That was an intermitent failure, it looks OK

Can you add a test for your new feature?

This looks pretty good otherwise!

**Comment by evantahler** [comment]
I've merged in your other pull requests, so you'll need to update this branch now

**Comment by bloublou2014** [comment]
Test Added for get/set

Note : test works under Elasticsearch 1.7.x but failed on parent/child with Elasticsearch 2.x since a breaking change.

**Comment by evantahler** [comment]
closing this PR as it has not been kept up-to-date.

**Comment by bloublou2014** [comment]
What has to be done to be included, last update from my part was to add test & test under elasticsearch. Do i need to update branch with your latest version, test again and pull again ?

**Comment by evantahler** [comment]
yeah, it's important that the tests pass and the PR can actually be merged.

**Comment by bloublou2014** [comment]
Ok, i will try to update to latest version and test again

**Pull request closed without merging**
