### PR TITLE
Fix to keep fields, such as _routing, from the base doc, which are not in doc.fields but where doc.fields exist. 

### PR DESCRIPTION
**Pull request by owenrh**
In the existing code, these are being dropped due to the if/else statement on _fields_ . As a result, we lose our _routing field. 

Sorry, no tests at the mo. I might be able to come back to them later.

### CODE REVIEW

**Comment by evantahler** [comment]
Thanks.   This will not be merged without tests, so provide them when you can!

**Comment by owenrh** [comment]
hey @evantahler, managed to together some tests. My node/js is a little rusty, but hopefully they do the job.

**Comment by evantahler** [comment]
This PR will need to be updated in order to merge

**Comment by evantahler** [comment]
Closing due to lack of progress

**Pull request closed without merging**
