### PR TITLE
use just scroll in GET serach

### PR DESCRIPTION
**Pull request by evantahler**
Finally removes `scan`, per https://github.com/taskrabbit/elasticsearch-dump/pull/202

### CODE REVIEW

**Comment by evantahler** [comment]
```
> npm publish
+ elasticdump@2.1.1
```

**Comment by LeeDr** [comment]
Thanks @evantahler !  I can confirm this elasticdump@2.1.1 is working on Elasticsearch master (5.0 ~alpha1).  I haven't gone back and tested on Elasticsearch 2.x builds yet but I would expect it's all good.

**Comment by vananiev** [comment]
Are you using sort: "_doc"? because speed of dumping decreased from 27Kdocs/s to 5Kdocs/s in my case in elasticdump-2.1.1 (CentOS-6.7).

**Comment by evantahler** [comment]
Yep, we knew that this behavior would slow down in ES 2, and then be greatly improved in ES 3/5, where they optimized that sort specifically. 

A great PR to add would be to determine the `--input` version of elasticsearch and decide how to handle that sort.  I'm also not personally sure if we need a sort at all... and it the use of `scroll` on its own will maintain the sort.   For elasticdump, we only need it to guarantee offsets via `skip`, so perhaps we can ignore the sort if there is no `--skip` option.

**Pull request merged**
