### PR TITLE
lib/transport/elasticsearch.js: Also include _routing and _parents fields during data import

### PR DESCRIPTION
**Pull request by fulax**
Hello,

I noticed that 0.13 actually dumps _parent and _routing fields, but they are not taken into account when restoring data from file, or directly from another index.

The following change adds both _routing and _parent value to both URI and buld insert.

### CODE REVIEW

**Comment by zecrazytux** [comment]
+1

**Comment by evantahler** [comment]
Cool!

I haven't used parent/child documents much, so I have a few questions/comments: 
- Is there ever a case where you might have `_parent` but not `_routing`?  Both of your changes assume both
- Can you please add a test.

**Comment by fulax** [comment]
My first approach looks like a quickfix to have my data restored from a previous dump :-)

I haven't use routing without parent, but the docs actually allows routing alone.  So I think a better approach would be to add all `fields` properties according to some whitelist based on https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_3 and https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-versioning :-)

I will update the PR and write some test.

**Comment by evantahler** [comment]
Bump! Any updates here?

**Comment by fulax** [comment]
Hello, sorry for the long delay, I needed to practice more NodeJS programming ;-)

I also found a bug while trying to dump & restore an index with two data types, only the mapping of the last dumped type was actually sent to ES, so I changed a bit the prototype in 19b255993e02eee794c1a9a2206a9aefea35a034 

About the tests, I wrote a pseed function, whose role is to create parents and childs objects.  I need to update tests to ensure the relationships are preserved between dumps and restores.

**Comment by evantahler** [comment]
cool, getting closer!  However, your test doesn't actually check any of your new options (as far as I can tell).  Do a dump asking for the new fields, and check they exist!

**Comment by henrik-m** [comment]
+1
Needed this right now. I am glad this pull request exists and hope you can finish it soon.

**Comment by evantahler** [comment]
re-ran tests; they are green.  Travis just had a hiccup.

**Comment by fulax** [comment]
Hi there.

Sorry for not having commented earlier. I had issue attempting to restore a parent-child index at work (the dump was OK), so i made minor adjustement about the underscore character preceding the fields parent/routing...

So the new changes works for dumping and restoring an index, but parent-child requires a specific mapping, so I had to write tests that first copy the mapping, then the data, that's why I created a separate test file (and to be sure I haven't break anything).

I think I could also add support for dumping & restoring the `version` metadata field, but I don't have any usecase where this piece of information is relevant.

**Comment by evantahler** [comment]
I don't think we need the version metadata.  That would be a separate issue anyway if someone needs it. 

@davidjairala any thoughts on this?  It looks good to me!

**Comment by evantahler** [comment]
Alright, merging!

**Pull request merged**
