### PR TITLE
Set inputType/outputType if using custom transport

### PR DESCRIPTION
**Pull request by TheDeveloper**
Fixes 'undefined' being printed out in logs.

screen shot 2015-12-22 at 16 54 50

### CODE REVIEW

**Comment by evantahler** [comment]
why wouldn't you use `String(self.options.inputTransport)` so you could get the name of what you passed in?

**Comment by TheDeveloper** [comment]
Good point, I don't see why not.

**Comment by evantahler** [comment]
Bump?

**Comment by evantahler** [comment]
closing in favor of https://github.com/taskrabbit/elasticsearch-dump/pull/140

**Comment by TheDeveloper** [comment]
Thanks. I think you meant #180

**Comment by evantahler** [comment]
Whoops! Updated

**Pull request closed without merging**
