### PR TITLE
Add params to Elasticsearch URI

### PR DESCRIPTION
**Pull request by prog8**
This is usefult for example when one needs to add shard preference

### CODE REVIEW

**Comment by prog8** [comment]
@evantahler is something like `params` going to be available in elasticsearch-dump or you think this just doesn't make sense?

**Comment by datashaman** [comment]
This does make sense, can you add a basic test which proves that the `params` are passed through appropriately?

**Comment by prog8** [comment]
@datashaman I added a test.

**Comment by prog8** [comment]
@datashaman @evantahler is it OK now?

**Comment by evantahler** [comment]
Looks good! Thank you for adding the test!

@datashaman I can see how this would matter in a large cluster... say you have a special node that you reserve just for "backend" tasks, like making snapshots and dumps, and you don't want to hurt the performance of the whole cluster.

**Comment by prog8** [comment]
> say you have a special node that you reserve just for "backend" tasks, like making snapshots and dumps, and you don't want to hurt the performance of the whole cluster.

Yes, this is one of use cases. Other is dumping only a subset of data or dumping data shard by shard or starting many processes in parallel (each reading from one shard only).

**Pull request merged**
